### ISSUE TITLE
pst-util problem

### ISSUE THREAD

**Issue by jorge80** [medale/spark-mail#6]
root@precise32:/spark-mail# java -classpath pst-utils/target/pst-utils-1.1.0-SNAPSHOT-shaded.jar com.uebercomputing.pst.Main --pstDir /vagrant/pst --avroOutDir /vagrant/tmp/ --overwrite true
Processing: /vagrant/pst/enron1.pst
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at com.uebercomputing.hadoop.HadoopUtils$.getLocalHadoopConfiguration(HadoopUtils.scala:33)
        at com.uebercomputing.hadoop.HadoopUtils$.<init>(HadoopUtils.scala:13)
        at com.uebercomputing.hadoop.HadoopUtils$.<clinit>(HadoopUtils.scala)
        at com.uebercomputing.pst.Main$$anonfun$main$1.apply(Main.scala:53)
        at com.uebercomputing.pst.Main$$anonfun$main$1.apply(Main.scala:48)
        at scala.Option.map(Option.scala:145)
        at com.uebercomputing.pst.Main$.main(Main.scala:48)
        at com.uebercomputing.pst.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

**Comment by medale** [comment]
Thanks for catching that! I had marked the hadoop dependency as provided in the parent pom and so it was not included in the pst-utils shaded jar anymore. For now, I removed the provided scope from hadoop. Please do a pull for that update and retry. Let me know if that fixed the problem for you also and I will close this issue.

**Comment by jorge80** [comment]
- to adjust pom and remove scope from hadoop? well still need to learn something new, anyway thank you and it works now like a charm
Input dir is /vagrant/pst
Output dir is /vagrant/tmp/test.avro
File system is file:///
WARN  NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Time to process /vagrant/pst/enron1.pst was 53 seconds and 854 milliseconds
Total time since start was 55 seconds and 88 milliseconds
Total runtime: 55 seconds and 131 milliseconds

**Comment by medale** [comment]
Glad it works now. The <scope> field controls whether the dependency is included in the shaded jar. Using "provided" means that the dependency (and its dependencies) are not included. They are assumed to be set up by some other framework (e.g. running the jar in Spark or Hadoop). Will close.
